package com.QC.demoQC.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

@Data
@Entity // this class act as entity
public class Question {
    @Id  // saying this is primary key
    @GeneratedValue(strategy = GenerationType.SEQUENCE) // for autogenerated
    private Integer id ;
    private  String questionTitle; // ORM will take care of camel case for database
    private  String option1 ;
    private String option2;
    private String option3;
    private String option4;
    private String rightAnswer ;
    private String difficultylevel;
    private  String category ;
}
